version: "3"

services:

  rabbitmq:
    container_name: rabbitqm
    image: rabbitmq:3.7.14-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 127.0.0.1:15672:15672
    restart: always

  elsa-demo:
    build:
      context: .
      args:
        - renderer-queue: elsa
        - elsa-queue: elsa-demo
        - rmq-connect: amqp://user:pass@localhost:5672
    container_name: elsa-demo
    networks:
      - host
    restart: always
